FROM python:3.12-alpine
RUN apk add --no-cache ffmpeg && \
    pip install --no-cache-dir yt-dlp
COPY stream-internet.sh /usr/local/bin/stream-internet.sh
RUN chmod +x /usr/local/bin/stream-internet.sh
ENTRYPOINT ["/usr/local/bin/stream-internet.sh"]
