FROM alpine:3.20
RUN apk add --no-cache ffmpeg python3 py3-pip && \
    pip install --no-cache-dir yt-dlp
COPY stream-internet.sh /usr/local/bin/stream-internet.sh
RUN chmod +x /usr/local/bin/stream-internet.sh
ENTRYPOINT ["/usr/local/bin/stream-internet.sh"]
