"""initial schema

Revision ID: 4187467d1edf
Revises: 
Create Date: 2026-06-03 22:31:55.495579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4187467d1edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_groups',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_group_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['camera_groups.id'], name='fk_camera_groups_parent_group_id_camera_groups'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_groups'))
    )
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mfa_secret', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_backup_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('preferred_timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('ui_preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('anonymised_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_users_created_by_users'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role_id_roles'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('allowed_ips', postgresql.ARRAY(sa.String(length=45)), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_api_keys_user_id_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'info'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_log_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('rtsp_main_url', sa.Text(), nullable=True),
    sa.Column('rtsp_sub_url', sa.Text(), nullable=True),
    sa.Column('onvif_port', sa.Integer(), server_default=sa.text('80'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('onvif_profile_main', sa.String(length=50), nullable=True),
    sa.Column('onvif_profile_sub', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('vpn_host', sa.String(length=45), nullable=True),
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('zone_location', sa.String(length=200), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'error', 'recording', 'unauthorized', 'unknown', name='camera_status_enum'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('recording_mode', sa.Enum('continuous', 'motion', 'scheduled', 'off', name='recording_mode_enum'), server_default=sa.text("'continuous'"), nullable=False),
    sa.Column('resolution_main', sa.String(length=20), nullable=True),
    sa.Column('resolution_sub', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.SmallInteger(), server_default=sa.text('25'), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), server_default=sa.text('2000'), nullable=False),
    sa.Column('codec', sa.Enum('h264', 'h265', 'mjpeg', name='codec_enum'), server_default=sa.text("'h264'"), nullable=False),
    sa.Column('retention_days', sa.SmallInteger(), server_default=sa.text('30'), nullable=False),
    sa.Column('pre_event_seconds', sa.SmallInteger(), server_default=sa.text('5'), nullable=False),
    sa.Column('post_event_seconds', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('ntp_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_ntp_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_errors', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('detection_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('privacy_mask', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ptz_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ptz_presets', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.CheckConstraint("ip_address ~ '^[0-9a-fA-F.:\\/]+$'", name=op.f('ck_cameras_ip_address_format')),
    sa.CheckConstraint("vpn_host IS NULL OR vpn_host ~ '^[0-9a-fA-F.:\\/]+$'", name=op.f('ck_cameras_vpn_host_format')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_cameras_created_by_users'),
    sa.ForeignKeyConstraint(['group_id'], ['camera_groups.id'], name='fk_cameras_group_id_camera_groups'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_ids', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=False),
    sa.Column('from_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', 'expired', name='export_status_enum'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('password_protected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('watermark', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('watermark_text', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='fk_export_jobs_requested_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=50), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sessions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('detection_types', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_enum'), nullable=False),
    sa.Column('schedule', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notification_channels', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_alert_rules_camera_id_cameras'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('camera_permissions',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('can_view_live', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_recordings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_export_clips', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_configure', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_ptz', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('granted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_camera_permissions_camera_id_cameras', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name='fk_camera_permissions_granted_by_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_camera_permissions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'camera_id', name=op.f('pk_camera_permissions'))
    )
    op.create_table('detection_zones',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('restricted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('dwell_threshold_s', sa.SmallInteger(), server_default=sa.text('30'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_detection_zones_camera_id_cameras', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_zones'))
    )
    op.create_table('recording_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('days_of_week', postgresql.ARRAY(sa.SmallInteger()), server_default=sa.text("'{}'::smallint[]"), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('recording_mode', sa.Enum('continuous', 'motion', 'scheduled', 'off', name='recording_mode_enum'), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_recording_schedules_camera_id_cameras', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_schedules'))
    )
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=True),
    sa.Column('zone_name', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity_enum'), nullable=False),
    sa.Column('rule_triggered', sa.String(length=100), nullable=True),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('frame_path', sa.Text(), nullable=True),
    sa.Column('clip_path', sa.Text(), nullable=True),
    sa.Column('clip_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_on_legal_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name='fk_alert_events_acknowledged_by_users'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name='fk_alert_events_alert_rule_id_alert_rules'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_alert_events_camera_id_cameras'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index('ix_alert_events_camera_triggered', 'alert_events', ['camera_id', 'triggered_at'], unique=False)
    op.create_index('ix_alert_events_triggered_at_brin', 'alert_events', ['triggered_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_alert_events_unacknowledged', 'alert_events', ['acknowledged', 'severity'], unique=False, postgresql_where=sa.text('acknowledged = FALSE'))
    op.create_table('recording_segments',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('segment_type', sa.Enum('continuous', 'motion', 'scheduled', 'event', 'manual', name='segment_type_enum'), nullable=True),
    sa.Column('has_motion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('motion_score', sa.Float(), nullable=True),
    sa.Column('has_alert', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('alert_event_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_corrupt', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_on_legal_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('width', sa.SmallInteger(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('fps', sa.SmallInteger(), nullable=True),
    sa.Column('codec', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_event_id'], ['alert_events.id'], name='fk_recording_segments_alert_event_id_alert_events'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='fk_recording_segments_camera_id_cameras', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recording_segments'))
    )
    op.create_index('ix_recording_segments_camera_time', 'recording_segments', ['camera_id', 'started_at', 'ended_at'], unique=False)
    op.create_index('ix_recording_segments_camera_type', 'recording_segments', ['camera_id', 'segment_type'], unique=False)
    op.create_index('ix_recording_segments_has_alert', 'recording_segments', ['has_alert'], unique=False, postgresql_where=sa.text('has_alert = TRUE'))
    op.create_index('ix_recording_segments_started_at_brin', 'recording_segments', ['started_at'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recording_segments_started_at_brin', table_name='recording_segments', postgresql_using='brin')
    op.drop_index('ix_recording_segments_has_alert', table_name='recording_segments', postgresql_where=sa.text('has_alert = TRUE'))
    op.drop_index('ix_recording_segments_camera_type', table_name='recording_segments')
    op.drop_index('ix_recording_segments_camera_time', table_name='recording_segments')
    op.drop_table('recording_segments')
    op.drop_index('ix_alert_events_unacknowledged', table_name='alert_events', postgresql_where=sa.text('acknowledged = FALSE'))
    op.drop_index('ix_alert_events_triggered_at_brin', table_name='alert_events', postgresql_using='brin')
    op.drop_index('ix_alert_events_camera_triggered', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('recording_schedules')
    op.drop_table('detection_zones')
    op.drop_table('camera_permissions')
    op.drop_table('alert_rules')
    op.drop_table('sessions')
    op.drop_table('export_jobs')
    op.drop_table('cameras')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('system_events')
    op.drop_table('roles')
    op.drop_table('notification_channels')
    op.drop_table('camera_groups')
    # ### end Alembic commands ###
